on:
  push:
    branches: [main]
name: Build and deploy on push
permissions:
  contents: write
jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: shalzz/zola-deploy-action
      uses: shalzz/zola-deploy-action@74526e63f38f84b82476349bbcd886b82040ff98 # v0.22.1
      env:
        PAGES_BRANCH: gh-pages
        BUILD_DIR: .
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
